trainer: # trainer params
  num_episodes: 1000
  test_freq: 200
  save_freq: 200
  use_curriculum: False
  rngseed: 123
  log_level: 1

tracker: # logging information for this trainer (maybe could go in its own config?)
  internal_plot: false
  wandb_plot: false
  render: false
  rolling_average_num: 250
  plt_frequency_seconds: 1

