# MAIN CONFIGS

defaults:
  - _self_
  - model: ppo
  - env: gym_hopper
  - trainer: base_trainer
  - logger: track
  - hydra: default
  - exp: default # should be last in this list, as it edits the above

wandb:
  project: motion-predictor
  job_type: train
  name: name-me ${now:%Y_%m_%d_%H_%M_%S}
  mode: online

device: cuda
seed: 123
