# MAIN CONFIGS

defaults:
  - _self_
  - model: dreamer
  - env: env.dmc_walker
  - hydra: default
  - exp: dreamer_demo # should be last in defaults list

run_name: "run"
savedir: ${run_name}

wandb:
  project: trustline-mp
  job_type: train
  name: ${run_name} ${exp_name} ${now:%Y_%m_%d_%H_%M_%S}
  mode: online

logger:
  log_rate: 25
  log_to_wandb: True
  log_to_terminal: True
  log_to_JSON: True
  json_logdir: ${savedir}
  json_filename: "metrics.jsonl"

device: cuda
seed: 123
